version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    expose:
      - "5432"

  redis:
    image: 'redis:alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    expose:
      - '6379'

  web:
    build: ./basic_flask
    ports:
      - "5000:5000"
    links:
      - db:db
    depends_on:
      - redis
      - db
    command: >
      sh -c "./manage.py init_db &&
             ./manage.py runserver --host 0.0.0.0"

  worker:
    build: ./basic_flask
    links:
      - db:db
      - redis:redis
    depends_on:
      - redis
      - db
    command: celery -A basic_app.celery worker -l info

volumes:
  postgres_data:
  redis:
