version:         '3.7'

services:
  db:
    image:       postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=realtors
    expose:
      - "5432"
    restart: always
    volumes:
      - ${REALTORS_PATH}/realtors:/var/lib/postgresql/data

  redis:
    image:       'redis:alpine'
    command:     redis-server
    expose:
      - '6379'

  web:
    build:       ./realtors
    ports:
      - "5000:5000"
    links:
      - db:db
    depends_on:
      - redis
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:postgres@db:5432/realtors
    restart: always
    command:     >
      sh -c "./manage.py init_db &&
             ./manage.py runserver --host 0.0.0.0"
    volumes:
      - '.:/realtors'

  worker:
    build:       ./realtors
    links:
      - db:db
      - redis:redis
    depends_on:
      - redis
      - db
    command:     celery -A basic_app.celery worker -l info
    environment:
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:postgres@db:5432/realtors
