"""realestate

Revision ID: b2a5ddf1da07
Revises: 35b593d48d6a
Create Date: 2019-11-19 11:40:46.392955
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b2a5ddf1da07'
down_revision = '35b593d48d6a'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
